# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Razão Social')),
                ('numero_documento', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('endereco_numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('codigo_municipio_tomador', models.CharField(max_length=7, verbose_name='Código do Município')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('iss_retido', models.IntegerField(help_text='1 - Sim, 2 - Não', verbose_name='ISS Retido')),
                ('item_lista', models.CharField(max_length=11, verbose_name='Atividade')),
                ('discriminacao', models.TextField(verbose_name='Descrição do Serviço')),
                ('codigo_municipio_servico', models.CharField(max_length=7, verbose_name='Código do Município')),
                ('codigo_cnae', models.IntegerField(verbose_name='Código CNAE')),
                ('codigo_tributacao_municipio', models.CharField(max_length=11, verbose_name='Código de Tributação')),
                ('aliquota', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Aliquota')),
                ('valor_deducoes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Deduções')),
                ('valor_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor PIS')),
                ('valor_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Cofins')),
                ('valor_inss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor INSS')),
                ('valor_ir', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor IR')),
                ('valor_csll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor CSLL')),
                ('outras_retencoes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Outras Retenções')),
                ('desconto_incondicionado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto Incondicionado')),
                ('desconto_condicionado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto Condicionado')),
                ('identificador', models.CharField(max_length=10, verbose_name='Identificador')),
                ('data_emissao', models.DateTimeField(verbose_name='Data Emissão')),
                ('simples', models.IntegerField(verbose_name='Simples')),
                ('incentivo', models.IntegerField(verbose_name='Incentivo')),
                ('numero', models.IntegerField(verbose_name='Número RPS')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
                ('natureza_operacao', models.IntegerField(verbose_name='Natureza Operação')),
                ('regime_especial', models.IntegerField(help_text='1 – Microempresa Municipal; 2 – Estimativa; 3 – Sociedade de Profissionais; 4 – Cooperativa', verbose_name='Regime Especial')),
                ('identificador_lote_rps', models.CharField(blank=True, max_length=10, verbose_name='Identificador')),
                ('numero_lote', models.IntegerField(blank=True, null=True, verbose_name='Número Lote')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('xml', models.TextField(blank=True, verbose_name='XML')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'RPS',
                'verbose_name_plural': 'RPSs',
            },
        ),
    ]
