# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rps',
            name='incentivo',
        ),
        migrations.AddField(
            model_name='rps',
            name='incentivador_cultural',
            field=models.BooleanField(default=False, verbose_name='Incentivador Cultural'),
        ),
        migrations.AlterField(
            model_name='rps',
            name='iss_retido',
            field=models.BooleanField(default=False, verbose_name='ISS Retido'),
        ),
        migrations.AlterField(
            model_name='rps',
            name='natureza_operacao',
            field=models.IntegerField(help_text='1 - Tributação no município, 2 - Tributação fora do município, 3 - Isenção, 4 - Imune, 5 - Exigibilidade suspensa por decisão judicial, 6 - Exigibilidade suspensa por procedimento administrativo', verbose_name='Natureza Operação'),
        ),
        migrations.AlterField(
            model_name='rps',
            name='regime_especial',
            field=models.IntegerField(help_text='1 - Microempresa Municipal, 2 - Estimativa, 3 - Sociedade de Profissionais, 4 - Cooperativa', verbose_name='Regime Especial'),
        ),
        migrations.AlterField(
            model_name='rps',
            name='simples',
            field=models.BooleanField(default=True, verbose_name='Simples'),
        ),
    ]
